# Generated by Django 5.1.4 on 2025-01-11 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_stocktransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocktransaction',
            options={},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={},
        ),
        migrations.AlterModelOptions(
            name='warehousestock',
            options={},
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='handled by'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='operation_type',
            field=models.CharField(choices=[('IN', 'In of stock'), ('OUT', 'Out of stock')], max_length=3, verbose_name='operation type'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='remark'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='time'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse', verbose_name='warehouse'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='location',
            field=models.TextField(blank=True, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='warehouse name'),
        ),
        migrations.AlterField(
            model_name='warehousestock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='warehousestock',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='stock'),
        ),
        migrations.AlterField(
            model_name='warehousestock',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse', verbose_name='warehouse'),
        ),
    ]
